using System;
using LiveLinq.Dictionary;

namespace LiveLinq.Examples.EntityFrameworkRepository.Task
{
    public interface IAutoGeneratedTaskRepository : IReadOnlyObservableDictionary<Guid, Task>
    {
    }
}